README.md: README.md
app.yaml: app.yaml
cloud_sql_proxy: cloud_sql_proxy
db.sqlite3: db.sqlite3
deployer.py: deployer.py
hse-physics: hse-physics
manage.py: manage.py
requirements.txt: requirements.txt
.gitignore: .idea/.gitignore
misc.xml: .idea/misc.xml
__init__.py: main/views/__init__.py
admin.py: main/admin.py
apps.py: main/apps.py
forms.py: main/forms/forms.py
models.py: accounts/models.py
tests.py: main/tests.py
urls.py: tasks/urls.py
views.py: accounts/views.py
asgi.py: tasks/asgi.py
settings.py: tasks/settings.py
wsgi.py: tasks/wsgi.py
signup.html: templates/signup.html
3m.log: extra/courses/3m.log
3m.md: extra/courses/3m.md
4m.html: extra/courses/4m.html
4m.md: extra/courses/4m.md
converter.bat: extra/courses/converter.bat
file.html: extra/courses/file.html
ann_write_form.py: main/forms/ann_write_form.py
user_info_forms.py: main/forms/user_info_forms.py
0001_initial.py: main/migrations/0001_initial.py
0002_markdownpage.py: main/migrations/0002_markdownpage.py
0003_block_coursepage_lecturer_block_and_more.py: main/migrations/0003_block_coursepage_lecturer_block_and_more.py
0004_alter_material_parent.py: main/migrations/0004_alter_material_parent.py
0005_alter_file_file_material.py: main/migrations/0005_alter_file_file_material.py
0006_alter_coursepage_lecturer_block_and_more.py: main/migrations/0006_alter_coursepage_lecturer_block_and_more.py
0007_markdownmat_alter_material_options.py: main/migrations/0007_markdownmat_alter_material_options.py
0008_file_uploaded_at.py: main/migrations/0008_file_uploaded_at.py
0009_announcement_name.py: main/migrations/0009_announcement_name.py
0010_alter_announcement_options_alter_material_options_and_more.py: main/migrations/0010_alter_announcement_options_alter_material_options_and_more.py
0011_materialcontainer_files.py: main/migrations/0011_materialcontainer_files.py
0012_iframe_materialcontainer_frames.py: main/migrations/0012_iframe_materialcontainer_frames.py
0013_remove_task_course_remove_profile_groups_and_more.py: main/migrations/0013_remove_task_course_remove_profile_groups_and_more.py
0014_markdownpage_name.py: main/migrations/0014_markdownpage_name.py
0015_coursepage_main_lecturer.py: main/migrations/0015_coursepage_main_lecturer.py
announcements.py: main/models/announcements.py
materials.py: main/models/materials.py
pages.py: main/models/pages.py
profiles.py: main/models/profiles.py
user.py: main/models/user.py
markdown.py: main/other/markdown.py
tags.py: main/templatetags/tags.py
announcement_view.py: main/views/announcement_view.py
course_views.py: main/views/course_views.py
markdown_page_view.py: main/views/markdown_page_view.py
profile_view.py: main/views/profile_view.py
Glava4.pdf: media/documents/Glava4.pdf
Glava9.pdf: media/documents/Glava9.pdf
Glava9_COiB0G5.pdf: media/documents/Glava9_COiB0G5.pdf
photo.jpg: media/profiles/photo.jpg
photo_RzEqnwa.jpg: media/profiles/photo_RzEqnwa.jpg
tex-mml-chtml.js: main/static/main/tex-mml-chtml.js
about.html: templates/main/about.html
announcements.html: templates/main/announcements.html
base.html: templates/main/base.html
base_form.html: templates/main/base_form.html
course_page.html: templates/main/course_page.html
create_course.html: templates/main/create_course.html
create_markdown_page.html: templates/main/create_markdown_page.html
index.html: templates/main/index.html
profile.html: templates/main/profile.html
view_markdown_page.html: templates/main/view_markdown_page.html
login.html: templates/registration/login.html
autocomplete.css: static/admin/css/autocomplete.css
base.css: static/admin/css/base.css
changelists.css: static/admin/css/changelists.css
dashboard.css: static/admin/css/dashboard.css
fonts.css: static/admin/css/fonts.css
forms.css: static/admin/css/forms.css
login.css: main/static/main/css/login.css
nav_sidebar.css: static/admin/css/nav_sidebar.css
responsive.css: static/admin/css/responsive.css
responsive_rtl.css: static/admin/css/responsive_rtl.css
rtl.css: static/admin/css/rtl.css
widgets.css: static/admin/css/widgets.css
LICENSE.txt: static/admin/js/vendor/xregexp/LICENSE.txt
README.txt: static/admin/img/README.txt
Roboto-Bold-webfont.woff: static/admin/fonts/Roboto-Bold-webfont.woff
Roboto-Light-webfont.woff: static/admin/fonts/Roboto-Light-webfont.woff
Roboto-Regular-webfont.woff: static/admin/fonts/Roboto-Regular-webfont.woff
LICENSE: static/admin/img/LICENSE
calendar-icons.svg: static/admin/img/calendar-icons.svg
icon-addlink.svg: static/admin/img/icon-addlink.svg
icon-alert.svg: static/admin/img/icon-alert.svg
icon-calendar.svg: static/admin/img/icon-calendar.svg
icon-changelink.svg: static/admin/img/icon-changelink.svg
icon-clock.svg: static/admin/img/icon-clock.svg
icon-deletelink.svg: static/admin/img/icon-deletelink.svg
icon-no.svg: static/admin/img/icon-no.svg
icon-unknown-alt.svg: static/admin/img/icon-unknown-alt.svg
icon-unknown.svg: static/admin/img/icon-unknown.svg
icon-viewlink.svg: static/admin/img/icon-viewlink.svg
icon-yes.svg: static/admin/img/icon-yes.svg
inline-delete.svg: static/admin/img/inline-delete.svg
search.svg: static/admin/img/search.svg
selector-icons.svg: static/admin/img/selector-icons.svg
sorting-icons.svg: static/admin/img/sorting-icons.svg
tooltag-add.svg: static/admin/img/tooltag-add.svg
tooltag-arrowright.svg: static/admin/img/tooltag-arrowright.svg
SelectBox.js: static/admin/js/SelectBox.js
SelectFilter2.js: static/admin/js/SelectFilter2.js
actions.js: static/admin/js/actions.js
autocomplete.js: static/admin/js/autocomplete.js
calendar.js: static/admin/js/calendar.js
cancel.js: static/admin/js/cancel.js
change_form.js: static/admin/js/change_form.js
collapse.js: static/admin/js/collapse.js
core.js: static/admin/js/core.js
inlines.js: static/admin/js/inlines.js
jquery.init.js: static/admin/js/jquery.init.js
nav_sidebar.js: static/admin/js/nav_sidebar.js
popup_response.js: static/admin/js/popup_response.js
prepopulate.js: static/admin/js/prepopulate.js
prepopulate_init.js: static/admin/js/prepopulate_init.js
urlify.js: static/admin/js/urlify.js
main.css: main/static/main/css/main.css
markdown.css: main/static/main/css/markdown.css
hse.jpeg: main/static/main/img/hse.jpeg
hse_main_page.png: static/main/img/hse_main_page.png
logo-blue.png: main/static/main/img/logo-blue.png
notification-bell-blue.png: main/static/main/img/notification-bell-blue.png
phys-logo-blue.png: main/static/main/img/phys-logo-blue.png
plus-blue.png: main/static/main/img/plus-blue.png
user-head-blue.png: main/static/main/img/user-head-blue.png
MathJax_AMS-Regular.woff: main/static/main/woff-v2/MathJax_AMS-Regular.woff
MathJax_Calligraphic-Bold.woff: main/static/main/woff-v2/MathJax_Calligraphic-Bold.woff
MathJax_Calligraphic-Regular.woff: main/static/main/woff-v2/MathJax_Calligraphic-Regular.woff
MathJax_Fraktur-Bold.woff: main/static/main/woff-v2/MathJax_Fraktur-Bold.woff
MathJax_Fraktur-Regular.woff: main/static/main/woff-v2/MathJax_Fraktur-Regular.woff
MathJax_Main-Bold.woff: main/static/main/woff-v2/MathJax_Main-Bold.woff
MathJax_Main-Italic.woff: main/static/main/woff-v2/MathJax_Main-Italic.woff
MathJax_Main-Regular.woff: main/static/main/woff-v2/MathJax_Main-Regular.woff
MathJax_Math-BoldItalic.woff: main/static/main/woff-v2/MathJax_Math-BoldItalic.woff
MathJax_Math-Italic.woff: main/static/main/woff-v2/MathJax_Math-Italic.woff
MathJax_Math-Regular.woff: main/static/main/woff-v2/MathJax_Math-Regular.woff
MathJax_SansSerif-Bold.woff: main/static/main/woff-v2/MathJax_SansSerif-Bold.woff
MathJax_SansSerif-Italic.woff: main/static/main/woff-v2/MathJax_SansSerif-Italic.woff
MathJax_SansSerif-Regular.woff: main/static/main/woff-v2/MathJax_SansSerif-Regular.woff
MathJax_Script-Regular.woff: main/static/main/woff-v2/MathJax_Script-Regular.woff
MathJax_Size1-Regular.woff: main/static/main/woff-v2/MathJax_Size1-Regular.woff
MathJax_Size2-Regular.woff: main/static/main/woff-v2/MathJax_Size2-Regular.woff
MathJax_Size3-Regular.woff: main/static/main/woff-v2/MathJax_Size3-Regular.woff
MathJax_Size4-Regular.woff: main/static/main/woff-v2/MathJax_Size4-Regular.woff
MathJax_Typewriter-Regular.woff: main/static/main/woff-v2/MathJax_Typewriter-Regular.woff
MathJax_Vector-Bold.woff: main/static/main/woff-v2/MathJax_Vector-Bold.woff
MathJax_Vector-Regular.woff: main/static/main/woff-v2/MathJax_Vector-Regular.woff
MathJax_Zero.woff: main/static/main/woff-v2/MathJax_Zero.woff
move_vertex_off.svg: static/admin/img/gis/move_vertex_off.svg
move_vertex_on.svg: static/admin/img/gis/move_vertex_on.svg
DateTimeShortcuts.js: static/admin/js/admin/DateTimeShortcuts.js
RelatedObjectLookups.js: static/admin/js/admin/RelatedObjectLookups.js
LICENSE-SELECT2.md: static/admin/css/vendor/select2/LICENSE-SELECT2.md
select2.css: static/admin/css/vendor/select2/select2.css
select2.min.css: static/admin/css/vendor/select2/select2.min.css
jquery.js: static/admin/js/vendor/jquery/jquery.js
jquery.min.js: static/admin/js/vendor/jquery/jquery.min.js
LICENSE.md: static/admin/js/vendor/select2/LICENSE.md
select2.full.js: static/admin/js/vendor/select2/select2.full.js
select2.full.min.js: static/admin/js/vendor/select2/select2.full.min.js
xregexp.js: static/admin/js/vendor/xregexp/xregexp.js
xregexp.min.js: static/admin/js/vendor/xregexp/xregexp.min.js
af.js: static/admin/js/vendor/select2/i18n/af.js
ar.js: static/admin/js/vendor/select2/i18n/ar.js
az.js: static/admin/js/vendor/select2/i18n/az.js
bg.js: static/admin/js/vendor/select2/i18n/bg.js
bn.js: static/admin/js/vendor/select2/i18n/bn.js
bs.js: static/admin/js/vendor/select2/i18n/bs.js
ca.js: static/admin/js/vendor/select2/i18n/ca.js
cs.js: static/admin/js/vendor/select2/i18n/cs.js
da.js: static/admin/js/vendor/select2/i18n/da.js
de.js: static/admin/js/vendor/select2/i18n/de.js
dsb.js: static/admin/js/vendor/select2/i18n/dsb.js
el.js: static/admin/js/vendor/select2/i18n/el.js
en.js: static/admin/js/vendor/select2/i18n/en.js
es.js: static/admin/js/vendor/select2/i18n/es.js
et.js: static/admin/js/vendor/select2/i18n/et.js
eu.js: static/admin/js/vendor/select2/i18n/eu.js
fa.js: static/admin/js/vendor/select2/i18n/fa.js
fi.js: static/admin/js/vendor/select2/i18n/fi.js
fr.js: static/admin/js/vendor/select2/i18n/fr.js
gl.js: static/admin/js/vendor/select2/i18n/gl.js
he.js: static/admin/js/vendor/select2/i18n/he.js
hi.js: static/admin/js/vendor/select2/i18n/hi.js
hr.js: static/admin/js/vendor/select2/i18n/hr.js
hsb.js: static/admin/js/vendor/select2/i18n/hsb.js
hu.js: static/admin/js/vendor/select2/i18n/hu.js
hy.js: static/admin/js/vendor/select2/i18n/hy.js
id.js: static/admin/js/vendor/select2/i18n/id.js
is.js: static/admin/js/vendor/select2/i18n/is.js
it.js: static/admin/js/vendor/select2/i18n/it.js
ja.js: static/admin/js/vendor/select2/i18n/ja.js
ka.js: static/admin/js/vendor/select2/i18n/ka.js
km.js: static/admin/js/vendor/select2/i18n/km.js
ko.js: static/admin/js/vendor/select2/i18n/ko.js
lt.js: static/admin/js/vendor/select2/i18n/lt.js
lv.js: static/admin/js/vendor/select2/i18n/lv.js
mk.js: static/admin/js/vendor/select2/i18n/mk.js
ms.js: static/admin/js/vendor/select2/i18n/ms.js
nb.js: static/admin/js/vendor/select2/i18n/nb.js
ne.js: static/admin/js/vendor/select2/i18n/ne.js
nl.js: static/admin/js/vendor/select2/i18n/nl.js
pl.js: static/admin/js/vendor/select2/i18n/pl.js
ps.js: static/admin/js/vendor/select2/i18n/ps.js
pt-BR.js: static/admin/js/vendor/select2/i18n/pt-BR.js
pt.js: static/admin/js/vendor/select2/i18n/pt.js
ro.js: static/admin/js/vendor/select2/i18n/ro.js
ru.js: static/admin/js/vendor/select2/i18n/ru.js
sk.js: static/admin/js/vendor/select2/i18n/sk.js
sl.js: static/admin/js/vendor/select2/i18n/sl.js
sq.js: static/admin/js/vendor/select2/i18n/sq.js
sr-Cyrl.js: static/admin/js/vendor/select2/i18n/sr-Cyrl.js
sr.js: static/admin/js/vendor/select2/i18n/sr.js
sv.js: static/admin/js/vendor/select2/i18n/sv.js
th.js: static/admin/js/vendor/select2/i18n/th.js
tk.js: static/admin/js/vendor/select2/i18n/tk.js
tr.js: static/admin/js/vendor/select2/i18n/tr.js
uk.js: static/admin/js/vendor/select2/i18n/uk.js
vi.js: static/admin/js/vendor/select2/i18n/vi.js
zh-CN.js: static/admin/js/vendor/select2/i18n/zh-CN.js
zh-TW.js: static/admin/js/vendor/select2/i18n/zh-TW.js