# Generated by Django 4.0.3 on 2022-05-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_markdownpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='coursepage',
            name='lecturer_block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='page_as_lect', to='main.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursepage',
            name='student_block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='page_as_st', to='main.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.block'),
            preserve_default=False,
        ),
    ]
