# Generated by Django 4.0.3 on 2022-05-30 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_block_coursepage_lecturer_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.block'),
        ),
    ]
