# Generated by Django 4.0.3 on 2022-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_markdownmat_alter_material_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
    ]
