# Generated by Django 4.0.3 on 2022-05-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_file_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='name',
            field=models.CharField(default='d_name', max_length=30),
            preserve_default=False,
        ),
    ]
