# Generated by Django 4.0.3 on 2022-06-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_announcement_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-id'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='default name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='text',
            field=models.TextField(default='default text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='default name', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file_material',
            field=models.FileField(null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='markdownmat',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MaterialContainer',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.material')),
                ('markdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.markdownmat')),
                ('urls', models.ManyToManyField(to='main.url')),
                ('videos', models.ManyToManyField(to='main.video')),
            ],
            bases=('main.material',),
        ),
    ]
