# Generated by Django 4.0.3 on 2022-06-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_materialcontainer_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFrame',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.material')),
                ('frame_url', models.URLField()),
            ],
            bases=('main.material',),
        ),
        migrations.AddField(
            model_name='materialcontainer',
            name='frames',
            field=models.ManyToManyField(to='main.iframe'),
        ),
    ]
