# Generated by Django 4.0.3 on 2022-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_task_course_remove_profile_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdownpage',
            name='name',
            field=models.CharField(default='Default name', max_length=50, verbose_name='Название страницы'),
            preserve_default=False,
        ),
    ]
